from .settings import (
    API_HOST,
    PORT,
    ENV,
    IS_PRODUCTION,
    ARTIFACTS_DIR,
    MODEL_BINARY_PATH,
    MODEL_MULTICLASS_PATH,
    METRICS_BINARY_PATH,
    METRICS_MULTICLASS_PATH,
    ALLOWED_HOSTS,
)
